//HintName: ValidationGenerated.g.cs
// <auto-generated/>
public static class ValidationLookups
{

public async ValueTask<object?> Validate(EndpointFilterInvocation context, EndpointFilterDelegate next)
{
    var todo = context.GetArgument<Todo>(0);
    var Id_RequiredAttribute = new System.ComponentModel.DataAnnotations.RequiredAttribute;
var Id_RangeAttribute = new System.ComponentModel.DataAnnotations.RangeAttribute(1, 2147483647);
var Title_RequiredAttribute = new System.ComponentModel.DataAnnotations.RequiredAttribute;
var Title_MinLengthAttribute = new System.ComponentModel.DataAnnotations.MinLengthAttribute(3);

    if (Id_RequiredAttribute.Validate(todo.Id))
{return Results.Problem("Validation problem detected in Id_RequiredAttribute")}if (Id_RangeAttribute.Validate(todo.Id))
{return Results.Problem("Validation problem detected in Id_RangeAttribute")}if (Title_RequiredAttribute.Validate(todo.Title))
{return Results.Problem("Validation problem detected in Title_RequiredAttribute")}if (Title_MinLengthAttribute.Validate(todo.Title))
{return Results.Problem("Validation problem detected in Title_MinLengthAttribute")}
    return StringNormalizationExtensions(context)
}}
