//HintName: Validations.ValidationFilters.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Builder;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;
public static partial class Validations
{
    public static TBuilder WithValidation<TBuilder>(this TBuilder builder, [CallerFilePath] string filePath = "", [CallerLineNumber] int lineNumber = 0) where TBuilder : IEndpointConventionBuilder
    {
        builder.AddEndpointFilter(Validations.Map[(filePath, lineNumber)]);
        return builder;
    }
    public static readonly System.Collections.Generic.Dictionary<(string, int), Func<EndpointFilterInvocationContext, EndpointFilterDelegate, ValueTask<object?>>> Map = new()
    {
        [("d57ed7b9-9143-4148-977b-64e3fc7098bf.cs", 9)] = async (EndpointFilterInvocationContext context, EndpointFilterDelegate next) =>
        {
            var results = new List<ValidationResult>();
            var id = context.GetArgument<int>(0);
            var validationContext = new ValidationContext(id);
            validationContext.MemberName = "id";
            validationContext.DisplayName = "id";
            var id_RequiredAttribute = new System.ComponentModel.DataAnnotations.RequiredAttribute();
            results.Add(id_RequiredAttribute.GetValidationResult(id, validationContext));
            var id_RangeAttribute = new System.ComponentModel.DataAnnotations.RangeAttribute(1,2147483647);
            results.Add(id_RangeAttribute.GetValidationResult(id, validationContext));
            var errors = new Dictionary<string, string[]>();
            foreach (var result in results)
            {
                if (result != ValidationResult.Success)
                {
                    errors.Add(result.MemberNames.SingleOrDefault(), new[] { result.ErrorMessage });
                }            }            if (errors.Count > 0)
            {
                return Results.ValidationProblem(errors);
            }
            return await next(context);
        },

    };
}
